version: "3"
services:
  app:
    image: node:latest
    ports:
      - 4173:4173 #preview server
      - 5173:5173 #dev server
    volumes:
      - .:/app
    tty: true
    working_dir: /app/my-vue-app
    command: sh -c "eval $(ssh-agent -s) && npm install && npm run dev"
