name: ESLint

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint and eslint-plugin-vue and typescript-eslint/eslint-plugin and typescript-eslint/parser
        run: |
          npm install eslint@8.57.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npm install eslint-plugin-vue@9.25.0
          npm install @vue/eslint-config-typescript@13.0.0
          npm install @typescript-eslint/eslint-plugin@7.8.0
          npm install @typescript-eslint/parser@7.8.0
      - name: Run ESLint
        run: |
          npx eslint .
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx,.vue
            --format json
            --output-file eslint-results.json
        continue-on-error: true
        working-directory: my-vue-app/src

      - name: Convert ESLint results to SARIF
        run: |
          npx @microsoft/eslint-formatter-sarif < eslint-results.json > eslint-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: eslint-results.sarif
