name: ESLint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: |
          npx eslint my-app-vue
            --config .eslintrc.js
            --ext .js,.jsx,.ts,.tsx
            --format json
            --output-file eslint-results.json
        continue-on-error: true

      - name: Convert ESLint results to SARIF
        run: |
          npx @microsoft/eslint-formatter-sarif < eslint-results.json > eslint-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: eslint-results.sarif