name: Assign Author

on:
  pull_request:
    types: [opened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign Author
        uses: technote-space/assign-author@v1.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
